import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { css } from "@emotion/react";
import { CoupleCard } from "@/components/CoupleCard";
import { renderToStaticMarkup } from "react-dom/server";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [femaleName, setFemaleName] = useState("Rina");
  const [femaleAge, setFemaleAge] = useState("27");
  const [femaleResidence, setFemaleResidence] = useState("兵庫県");
  const [femaleJob, setFemaleJob] = useState("モデル");
  const [femaleHobby, setFemaleHobby] = useState("ワイン、お笑い、ダンス、DIY");
  const [maleName, setMaleName] = useState("Shigeyasu");
  const [maleAge, setMaleAge] = useState("27");
  const [maleResidence, setMaleResidence] = useState("滋賀県");
  const [maleJob, setMaleJob] = useState("会社員");
  const [maleHobby, setMaleHobby] = useState("麻雀、お笑い、フットサル");

  return (
    <>
      <Head>
        <title>Plain HTML Components</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        css={css`
          padding-left: 20px;
          padding-right: 20px;
          @media (min-width: 1024px) {
            margin-left: auto;
            margin-right: auto;
            width: 712px;
            padding: 0;
          }
        `}
        className={`${styles.main} ${inter.className}`}
      >
        <section>
          <CoupleCard
            femaleName={femaleName}
            femaleAge={femaleAge}
            femaleResidence={femaleResidence}
            femaleJob={femaleJob}
            femaleHobby={femaleHobby}
            maleName={maleName}
            maleAge={maleAge}
            maleResidence={maleResidence}
            maleJob={maleJob}
            maleHobby={maleHobby}
          />
        </section>

        <section
          css={css`
            padding: 24px;
            display: flex;
          `}
        >
          <fieldset>
            <legend>女性</legend>
            <div>
              <label htmlFor="female-name">名前</label>
              <input
                type="text"
                id="female-name"
                name="female-name"
                value={femaleName}
                onChange={(event) => setFemaleName(event.target.value)}
              />
            </div>
            <div>
              <label htmlFor="female-age">年齢</label>
              <input
                type="text"
                id="female-age"
                name="female-age"
                value={femaleAge}
                onChange={(event) => setFemaleAge(event.target.value)}
              />
            </div>
            <div>
              <label htmlFor="female-residence">居住地</label>
              <input
                type="text"
                id="female-residence"
                name="female-residence"
                value={femaleResidence}
                onChange={(event) => setFemaleResidence(event.target.value)}
              />
            </div>
            <label htmlFor="female-job">職業</label>
            <input
              type="text"
              id="female-job"
              name="female-job"
              value={femaleJob}
              onChange={(event) => setFemaleJob(event.target.value)}
            />
            <div>
              <label htmlFor="female-hobby">趣味</label>
              <input
                type="text"
                id="female-hobby"
                name="female-hobby"
                value={femaleHobby}
                onChange={(event) => setFemaleHobby(event.target.value)}
              />
            </div>
          </fieldset>
          <fieldset>
            <legend>男性</legend>
            <div>
              <label htmlFor="male-name">名前</label>
              <input
                type="text"
                id="male-name"
                name="male-name"
                value={maleName}
                onChange={(event) => setMaleName(event.target.value)}
              />
            </div>
            <div>
              <label htmlFor="male-age">年齢</label>
              <input
                type="text"
                id="male-age"
                name="male-age"
                value={maleAge}
                onChange={(event) => setMaleAge(event.target.value)}
              />
            </div>
            <div>
              <label htmlFor="male-residence">居住地</label>
              <input
                type="text"
                id="male-residence"
                name="male-residence"
                value={maleResidence}
                onChange={(event) => setMaleResidence(event.target.value)}
              />
            </div>
            <label htmlFor="male-job">職業</label>
            <input
              type="text"
              id="male-job"
              name="male-job"
              value={maleJob}
              onChange={(event) => setMaleJob(event.target.value)}
            />
            <div>
              <label htmlFor="male-hobby">趣味</label>
              <input
                type="text"
                id="male-hobby"
                name="male-hobby"
                value={maleHobby}
                onChange={(event) => setMaleHobby(event.target.value)}
              />
            </div>
          </fieldset>
        </section>

        <section>
          <textarea
            cols={100}
            css={css`
              width: 100%;
              height: 30vh;
            `}
            defaultValue={renderToStaticMarkup(
              <CoupleCard
                femaleName={femaleName}
                femaleAge={femaleAge}
                femaleResidence={femaleResidence}
                femaleJob={femaleJob}
                femaleHobby={femaleHobby}
                maleName={maleName}
                maleAge={maleAge}
                maleResidence={maleResidence}
                maleJob={maleJob}
                maleHobby={maleHobby}
              />
            )}
          ></textarea>
        </section>
      </main>
    </>
  );
}
