import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { css } from "@emotion/react";
import { CoupleCard } from "@/components/CoupleCard";
import { renderToStaticMarkup } from "react-dom/server";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Plain HTML Components</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        css={css`
          padding-left: 20px;
          padding-right: 20px;
          @media (min-width: 1024px) {
            margin-left: auto;
            margin-right: auto;
            width: 712px;
            padding: 0;
          }
        `}
        className={`${styles.main} ${inter.className}`}
      >
        <section>
          <CoupleCard />
        </section>

        <section>
          <textarea
            cols={40}
            rows={100}
            css={css`
              margin: 24px;
            `}
            defaultValue={renderToStaticMarkup(<CoupleCard />)}
          ></textarea>
        </section>
      </main>
    </>
  );
}
